os:
  name: alpine
origin: alp/copy
device-template: alp
users:
    - name: user1
      uid: 2001
      shell: /bin/bash
      sudo: true
      ssh: true
      groups:
        - wheel
        - adm
filesystems:
  main:
    pattern: (zfsroot)/(project/)host/(instance)
devices:
  home:
    path: /home
    filesystem: main

